[[redirects]]
  from = "/"
  to = "/en"
  status = 301
  force = true
  conditions = {Language = ["en"]}

[[redirects]]
  from = "/"
  to = "/es"
  status = 301
  force = true
  conditions = {Language = ["es"]}

[build]
  publish = "public"
  command = "hugo --gc --cleanDestinationDir"